import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { JsonLd } from "@/components/JsonLd";
import { getStory, stories } from "@/data/content";

export function generateStaticParams() { return stories.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const story = getStory((await params).slug); return story ? { title: story.title, description: story.excerpt } : {}; }
export default async function StoryPage({ params }: { params: Promise<{ slug: string }> }) { const story = getStory((await params).slug); if (!story) notFound(); return <main id="contenido"><JsonLd data={{ "@context": "https://schema.org", "@type": "Article", headline: story.title, datePublished: "2026-09-21", author: { "@type": "Organization", name: "Experiencias ConSentido" } }} /><article className="article-page"><Link className="back-link" href="/cholula/historias">← Todas las historias</Link><p className="eyebrow">{story.category} · {story.readingTime}</p><h1>{story.title}</h1><p className="page-lead">{story.excerpt}</p><div className="article-body"><p>Viajar no empieza al llegar. Empieza cuando decidimos qué información buscamos, a quién escuchamos y cómo nos relacionamos con el lugar que nos recibe.</p><h2>Mirar más allá del escenario</h2><p>Cholula no es únicamente una colección de imágenes reconocibles. Es un territorio habitado, con ritmos, oficios, celebraciones y límites. Una experiencia con sentido ayuda a comprender esa complejidad sin convertirla en espectáculo.</p><blockquote>Conocer también es reconocer la autoría, el trabajo y el cuidado detrás de cada encuentro.</blockquote><p>Esta sección editorial crecerá con entrevistas, fuentes y permisos expresos. Cada historia indicará quién la escribió, quién colaboró y cuándo fue actualizada.</p></div><footer className="article-byline">Publicado por Experiencias ConSentido · {story.publishedAt}</footer></article></main>; }
