import type { Metadata } from "next";
import { PageHero } from "@/components/PageHero";
import { experiences } from "@/data/content";

export const metadata: Metadata = { title: "Cholula transparente", description: "Indicadores agregados y metodología de actualización de Experiencias ConSentido Cholula." };
export default function TransparencyPage() {
  const accessible = experiences.filter((item) => item.accessible).length; const free = experiences.filter((item) => item.free).length;
  return <main id="contenido"><PageHero eyebrow="INFORMACIÓN AGREGADA" title="Cholula transparente." description="Datos para comprender la oferta publicada sin exponer información privada, comercial o sensible de sus participantes." back={{ label: "Edición Cholula", href: "/cholula" }} /><section className="section surface"><div className="notice wide"><strong>Datos iniciales de demostración</strong><p>Los indicadores actuales describen únicamente las fichas de muestra del prototipo. No representan todavía el universo turístico de Cholula.</p></div><div className="metrics-grid"><article><strong>{experiences.length}</strong><span>fichas de muestra</span></article><article><strong>0</strong><span>reconocimientos emitidos</span></article><article><strong>{accessible}</strong><span>con accesibilidad inicial</span></article><article><strong>{free}</strong><span>de acceso libre</span></article></div><div className="detail-grid"><section><p className="eyebrow">QUÉ PUBLICAREMOS</p><h2>Indicadores útiles para el destino.</h2><ul className="feature-list"><li>Distribución por categoría y zona</li><li>Rangos de precio y duración</li><li>Accesibilidad documentada</li><li>Prácticas sostenibles</li><li>Participación de productores locales</li><li>Estacionalidad e impacto comunitario</li></ul></section><section><p className="eyebrow">QUÉ PROTEGEREMOS</p><h2>Transparencia sin vulnerabilidad.</h2><ul className="feature-list"><li>Datos personales y comerciales</li><li>Ubicación de espacios sensibles</li><li>Evaluaciones internas individuales</li><li>Historias o fotografías sin permiso</li><li>Información que facilite apropiación o explotación</li></ul></section></div></section></main>;
}
